name: API Tests

on:
  push:
    branches:
      - amir
  pull_request:
    branches:
      - amir

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip > install.log 2>&1
        pip install pytest requests flask ruamel.yaml kubernetes docker flask-cors >> install.log 2>&1
        echo "Dependencies installed. Check install.log for details."
      
    - name: Verify Flask Installation
      run: |
        python -c "import importlib.metadata; print(f'Flask version: {importlib.metadata.version(\"flask\")}')"

    - name: Check Python Syntax
      run: |
        find backend/ -name "*.py" -print0 | xargs -0 -n1 python -m py_compile

    - name: Run API Finder Script
      run: |
        echo "Running Flask server detection...ğŸ”"
        python tests/api_finder.py > flask-server-results.txt
        cat flask-server-results.txt
      shell: /usr/bin/bash -e {0}

    - name: Run Tests
      run: |
        echo "Running API validation tests...ğŸƒğŸ½"
        pytest tests/clusters_test.py tests/imageShow_test.py tests/postReq_test.py tests/server_test.py tests/copyImage_test.py tests/migration_test.py --disable-warnings > api-validation-results.txt || exit_code=$?
        cat api-validation-results.txt
        if [ $exit_code -ne 0 ]; then
          echo "Tests failed! Analyzing failed tests...ğŸ”"
          grep -E "^FAIL|^ERROR" api-validation-results.txt
          exit $exit_code
        fi

    - name: Print Test Status
      if: failure()
      run: |
        echo "API validation tests failed! âŒğŸ’€. Please check the results above."

    - name: Final Message
      if: success()
      run: echo "All tests passed successfully! âœ…ğŸ¤—"
